services:
  db:
    profiles: [ "dev", "all" ]
    image: timescale/timescaledb:latest-pg17
    ports: [ "5434:5432" ]
    restart: unless-stopped
    expose: [ "5432" ]
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d/:ro

  grafana:
    profiles: [ "dev", "all" ]
    restart: unless-stopped
    image: grafana/grafana
    ports: [ "3000:3000" ]
    expose: [ "3000" ]
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro

    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
      GF_SERVER_ROOT_URL: https://dashboard.regenfass.eu
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD:-admin}"

  backend:
    profiles: [ "all" ]
    build: .
    restart: unless-stopped
    expose: [ "64000" ]
    ports: [ "64000:64000/tcp" ]
    command:
      - --listen-addr=:64000
      - --database-uri=postgres://postgres:password@db:5432/regenfass?sslmode=disable

volumes:
  db-data:
  grafana-data:
