apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    orgId: 1
    uid: "default_timescale_ds"
    isDefault: true
    url: db:5432
    user: postgres
    secureJsonData:
      password: 'password'
    jsonData:
      database: regenfass
      timeInterval: 30s
      sslmode: disable
      postgresVersion: 1710
      timescaledb: true
