// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO device (device_eui) VALUES (UPPER($1)) RETURNING id, rw_token, ro_token
`

type CreateDeviceRow struct {
	ID      pgtype.UUID
	RwToken string
	RoToken string
}

func (q *Queries) CreateDevice(ctx context.Context, upper interface{}) (CreateDeviceRow, error) {
	row := q.db.QueryRow(ctx, createDevice, upper)
	var i CreateDeviceRow
	err := row.Scan(&i.ID, &i.RwToken, &i.RoToken)
	return i, err
}

const getChannelMappingsForDeviceIDs = `-- name: GetChannelMappingsForDeviceIDs :many
SELECT device_id, channel_id, name, measurement_type, hidden
FROM device_channel_mapping
WHERE device_id = ANY($1::UUID[])
ORDER BY device_id, channel_id
`

// Every channel of the given devices that someone has described or hidden,
// including channels that have never carried a measurement. Lets the dashboard
// show a declared slot as an empty labelled card until the device starts
// reporting on it, and know which channels are hidden so they can be restored.
func (q *Queries) GetChannelMappingsForDeviceIDs(ctx context.Context, deviceIds []pgtype.UUID) ([]DeviceChannelMapping, error) {
	rows, err := q.db.Query(ctx, getChannelMappingsForDeviceIDs, deviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceChannelMapping
	for rows.Next() {
		var i DeviceChannelMapping
		if err := rows.Scan(
			&i.DeviceID,
			&i.ChannelID,
			&i.Name,
			&i.MeasurementType,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceByEUI = `-- name: GetDeviceByEUI :one
SELECT id, device_eui, rw_token, ro_token, name, latitude, longitude FROM device WHERE device_eui = UPPER($1)
`

func (q *Queries) GetDeviceByEUI(ctx context.Context, upper interface{}) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByEUI, upper)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceEui,
		&i.RwToken,
		&i.RoToken,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getDeviceByEitherToken = `-- name: GetDeviceByEitherToken :one
SELECT id, device_eui, rw_token, ro_token, name, latitude, longitude, (ro_token = $1) AS is_readonly FROM device WHERE ro_token = $1 OR rw_token = $1
`

type GetDeviceByEitherTokenRow struct {
	ID         pgtype.UUID
	DeviceEui  string
	RwToken    string
	RoToken    string
	Name       string
	Latitude   pgtype.Float8
	Longitude  pgtype.Float8
	IsReadonly bool
}

func (q *Queries) GetDeviceByEitherToken(ctx context.Context, roToken string) (GetDeviceByEitherTokenRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByEitherToken, roToken)
	var i GetDeviceByEitherTokenRow
	err := row.Scan(
		&i.ID,
		&i.DeviceEui,
		&i.RwToken,
		&i.RoToken,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.IsReadonly,
	)
	return i, err
}

const getDevicesForDeviceTokens = `-- name: GetDevicesForDeviceTokens :many
SELECT d.id, d.device_eui, d.name, d.latitude, d.longitude, (d.ro_token = t.token) AS is_readonly
FROM unnest($1::TEXT[]) AS t(token)
JOIN device d ON d.ro_token = t.token OR d.rw_token = t.token
`

type GetDevicesForDeviceTokensRow struct {
	ID         pgtype.UUID
	DeviceEui  string
	Name       string
	Latitude   pgtype.Float8
	Longitude  pgtype.Float8
	IsReadonly bool
}

// Resolve each provided device token (read-write or read-only) to its device.
// `is_readonly` reflects whether the provided token was the read-only token.
func (q *Queries) GetDevicesForDeviceTokens(ctx context.Context, deviceTokens []string) ([]GetDevicesForDeviceTokensRow, error) {
	rows, err := q.db.Query(ctx, getDevicesForDeviceTokens, deviceTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesForDeviceTokensRow
	for rows.Next() {
		var i GetDevicesForDeviceTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceEui,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.IsReadonly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceChannelHidden = `-- name: SetDeviceChannelHidden :exec
INSERT INTO device_channel_mapping (device_id, channel_id, hidden)
VALUES ($1, $2, $3)
ON CONFLICT (device_id, channel_id) DO UPDATE
SET hidden = EXCLUDED.hidden
`

type SetDeviceChannelHiddenParams struct {
	DeviceID  pgtype.UUID
	ChannelID int16
	Hidden    bool
}

// Takes a channel off the dashboard, or puts it back. Nothing is deleted: the
// measurements stay and keep arriving, they are just not rendered. Hiding a
// channel nobody has described creates the row for the flag alone.
func (q *Queries) SetDeviceChannelHidden(ctx context.Context, arg SetDeviceChannelHiddenParams) error {
	_, err := q.db.Exec(ctx, setDeviceChannelHidden, arg.DeviceID, arg.ChannelID, arg.Hidden)
	return err
}

const updateDeviceLocation = `-- name: UpdateDeviceLocation :exec
UPDATE device SET latitude = $2, longitude = $3 WHERE id = $1
`

type UpdateDeviceLocationParams struct {
	ID        pgtype.UUID
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
}

func (q *Queries) UpdateDeviceLocation(ctx context.Context, arg UpdateDeviceLocationParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLocation, arg.ID, arg.Latitude, arg.Longitude)
	return err
}

const updateDeviceName = `-- name: UpdateDeviceName :exec
UPDATE device SET name = $2 WHERE id = $1
`

type UpdateDeviceNameParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) error {
	_, err := q.db.Exec(ctx, updateDeviceName, arg.ID, arg.Name)
	return err
}

const upsertDeviceChannelMapping = `-- name: UpsertDeviceChannelMapping :exec
INSERT INTO device_channel_mapping (device_id, channel_id, name, measurement_type)
VALUES ($1, $2, $3::TEXT, $4::SMALLINT)
ON CONFLICT (device_id, channel_id) DO UPDATE
SET name = EXCLUDED.name, measurement_type = EXCLUDED.measurement_type
`

type UpsertDeviceChannelMappingParams struct {
	DeviceID        pgtype.UUID
	ChannelID       int16
	Name            pgtype.Text
	MeasurementType pgtype.Int2
}

// Writes the description the user gave a channel in the dashboard's slot
// editor. The row may not exist yet: a channel can be described before the
// device has ever reported on it, which is the point of the editor.
func (q *Queries) UpsertDeviceChannelMapping(ctx context.Context, arg UpsertDeviceChannelMappingParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceChannelMapping,
		arg.DeviceID,
		arg.ChannelID,
		arg.Name,
		arg.MeasurementType,
	)
	return err
}
