// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/device/{deviceToken}": {
            "get": {
                "description": "Retrieve device details using either read-write or read-only token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Get device information by token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device token (read-write or read-only)",
                        "name": "deviceToken",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DeviceInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid token",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    }
                }
            }
        },
        "/group": {
            "post": {
                "description": "Create a new device group for organizing rain barrel devices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Create a new group",
                "parameters": [
                    {
                        "description": "Group name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateGroupPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.CreateGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    }
                }
            }
        },
        "/group/{groupToken}": {
            "get": {
                "description": "Retrieve group details and associated devices using either read-write or read-only token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get group information by token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group token (read-write or read-only)",
                        "name": "groupToken",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GroupInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid group token",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    }
                }
            }
        },
        "/group/{groupToken}/devices": {
            "post": {
                "description": "Add an existing device to a group using the group's read-write token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Add device to group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group read-write token",
                        "name": "groupToken",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Device token to add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AddDeviceToGroupPayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid token or payload",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Group token is read-only",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Check if the API and database connection are healthy",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "database connection unhealthy",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ingest": {
            "post": {
                "description": "Process LoRaWAN uplink messages and store device measurements",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingest"
                ],
                "summary": "Ingest LoRaWAN uplink data",
                "parameters": [
                    {
                        "description": "LoRaWAN uplink message",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IngestRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AddDeviceToGroupPayload": {
            "description": "Request body to add a device to an existing group",
            "type": "object",
            "properties": {
                "device_token": {
                    "type": "string",
                    "example": "device_token_123"
                }
            }
        },
        "api.CreateGroupPayload": {
            "description": "Request body to create a new device group",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "My Rain Barrel Group"
                }
            }
        },
        "api.CreateGroupResponse": {
            "description": "Response with group ID and tokens",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "read_only_token": {
                    "type": "string",
                    "example": "ro_group_token_123"
                },
                "read_write_token": {
                    "type": "string",
                    "example": "rw_group_token_123"
                }
            }
        },
        "api.DeviceInfoResponse": {
            "type": "object",
            "properties": {
                "device_eui": {
                    "type": "string",
                    "example": "AABBCCDDEEFF0011"
                },
                "read_only_token": {
                    "type": "string",
                    "example": "ro_token_123"
                },
                "read_write_token": {
                    "type": "string",
                    "example": "rw_token_123"
                },
                "token": {
                    "type": "string",
                    "example": "dev_token_123"
                }
            }
        },
        "api.GroupInfoDevice": {
            "description": "Device information within a group",
            "type": "object",
            "properties": {
                "is_readonly": {
                    "type": "boolean",
                    "example": false
                },
                "token": {
                    "type": "string",
                    "example": "device_token_123"
                }
            }
        },
        "api.GroupInfoResponse": {
            "description": "Detailed group information including associated devices",
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.GroupInfoDevice"
                    }
                },
                "is_readonly": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "My Rain Barrel Group"
                }
            }
        },
        "api.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "api.IngestRequest": {
            "description": "Request body for ingesting device measurements from LoRaWAN uplink messages",
            "type": "object",
            "properties": {
                "end_device_ids": {
                    "type": "object",
                    "properties": {
                        "dev_eui": {
                            "type": "string",
                            "example": "1234567890123456"
                        }
                    }
                },
                "uplink_message": {
                    "type": "object",
                    "properties": {
                        "frm_payload": {
                            "type": "string",
                            "example": "AQIDBA=="
                        },
                        "received_at": {
                            "type": "string",
                            "example": "2024-01-15T10:30:00Z"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:64000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Regenfass API",
	Description:      "API for managing LoRaWAN rain barrel devices and sensor data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
