// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertDeviceMeasurements implements pgx.CopyFromSource.
type iteratorForInsertDeviceMeasurements struct {
	rows                 []InsertDeviceMeasurementsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDeviceMeasurements) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDeviceMeasurements) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DeviceID,
		r.rows[0].Type,
		r.rows[0].ChannelID,
		r.rows[0].Value,
		r.rows[0].ReceivedAt,
	}, nil
}

func (r iteratorForInsertDeviceMeasurements) Err() error {
	return nil
}

func (q *Queries) InsertDeviceMeasurements(ctx context.Context, arg []InsertDeviceMeasurementsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"device_measurement"}, []string{"device_id", "type", "channel_id", "value", "received_at"}, &iteratorForInsertDeviceMeasurements{rows: arg})
}
