// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO device (device_eui) VALUES (UPPER($1)) RETURNING id, rw_token, ro_token
`

type CreateDeviceRow struct {
	ID      pgtype.UUID
	RwToken string
	RoToken string
}

func (q *Queries) CreateDevice(ctx context.Context, upper interface{}) (CreateDeviceRow, error) {
	row := q.db.QueryRow(ctx, createDevice, upper)
	var i CreateDeviceRow
	err := row.Scan(&i.ID, &i.RwToken, &i.RoToken)
	return i, err
}

const ensureDeviceChannelMapping = `-- name: EnsureDeviceChannelMapping :exec
INSERT INTO device_channel_mapping (device_id, channel_id, name)
VALUES ($1, $2, 'Unmapped')
ON CONFLICT (device_id, channel_id) DO NOTHING
`

type EnsureDeviceChannelMappingParams struct {
	DeviceID  pgtype.UUID
	ChannelID int16
}

func (q *Queries) EnsureDeviceChannelMapping(ctx context.Context, arg EnsureDeviceChannelMappingParams) error {
	_, err := q.db.Exec(ctx, ensureDeviceChannelMapping, arg.DeviceID, arg.ChannelID)
	return err
}

const getDeviceByEUI = `-- name: GetDeviceByEUI :one
SELECT id, device_eui, rw_token, ro_token, name, latitude, longitude FROM device WHERE device_eui = UPPER($1)
`

func (q *Queries) GetDeviceByEUI(ctx context.Context, upper interface{}) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByEUI, upper)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceEui,
		&i.RwToken,
		&i.RoToken,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getDeviceByEitherToken = `-- name: GetDeviceByEitherToken :one
SELECT id, device_eui, rw_token, ro_token, name, latitude, longitude, (ro_token = $1) AS is_readonly FROM device WHERE ro_token = $1 OR rw_token = $1
`

type GetDeviceByEitherTokenRow struct {
	ID         pgtype.UUID
	DeviceEui  string
	RwToken    string
	RoToken    string
	Name       string
	Latitude   pgtype.Float8
	Longitude  pgtype.Float8
	IsReadonly bool
}

func (q *Queries) GetDeviceByEitherToken(ctx context.Context, roToken string) (GetDeviceByEitherTokenRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByEitherToken, roToken)
	var i GetDeviceByEitherTokenRow
	err := row.Scan(
		&i.ID,
		&i.DeviceEui,
		&i.RwToken,
		&i.RoToken,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.IsReadonly,
	)
	return i, err
}
