// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceByEUI = `-- name: GetDeviceByEUI :one
SELECT id, device_eui, rw_token, ro_token FROM device WHERE device_eui = $1
`

func (q *Queries) GetDeviceByEUI(ctx context.Context, deviceEui string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByEUI, deviceEui)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceEui,
		&i.RwToken,
		&i.RoToken,
	)
	return i, err
}

const getDeviceByEitherToken = `-- name: GetDeviceByEitherToken :one
SELECT id, device_eui, rw_token, ro_token, (ro_token = $1) AS is_readonly FROM device WHERE ro_token = $1 OR rw_token = $1
`

type GetDeviceByEitherTokenRow struct {
	ID         pgtype.UUID
	DeviceEui  string
	RwToken    string
	RoToken    string
	IsReadonly bool
}

func (q *Queries) GetDeviceByEitherToken(ctx context.Context, roToken string) (GetDeviceByEitherTokenRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByEitherToken, roToken)
	var i GetDeviceByEitherTokenRow
	err := row.Scan(
		&i.ID,
		&i.DeviceEui,
		&i.RwToken,
		&i.RoToken,
		&i.IsReadonly,
	)
	return i, err
}
