// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceByEUI = `-- name: GetDeviceByEUI :one
SELECT id, device_eui, minimum_level FROM device WHERE device_eui = $1
`

func (q *Queries) GetDeviceByEUI(ctx context.Context, deviceEui string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByEUI, deviceEui)
	var i Device
	err := row.Scan(&i.ID, &i.DeviceEui, &i.MinimumLevel)
	return i, err
}

const updateDeviceMinimumLevel = `-- name: UpdateDeviceMinimumLevel :one
UPDATE device SET minimum_level = $2 WHERE device_eui = $1 RETURNING id
`

type UpdateDeviceMinimumLevelParams struct {
	DeviceEui    string
	MinimumLevel float64
}

func (q *Queries) UpdateDeviceMinimumLevel(ctx context.Context, arg UpdateDeviceMinimumLevelParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateDeviceMinimumLevel, arg.DeviceEui, arg.MinimumLevel)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
