// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceMeasurementsRanged = `-- name: GetDeviceMeasurementsRanged :many
SELECT DISTINCT ON (m.channel_id, m.bucket)
	m.received_at,
	m.channel_id,
	m.channel_name,
	m.measurement_type,
	m.value
FROM (
	SELECT
		time_bucket(make_interval(secs => $1::DOUBLE PRECISION), dm.received_at) AS bucket,
		dm.received_at,
		dm.channel_id,
		dcm.name AS channel_name,
		dm.measurement_type,
		dm.value
	FROM device_measurement dm
	JOIN device_channel_mapping dcm
		ON dcm.device_id = dm.device_id AND dcm.channel_id = dm.channel_id
	WHERE dm.device_id = $2
		AND dm.received_at >= $3
		AND dm.received_at <= $4
		AND ($5::SMALLINT IS NULL OR dm.channel_id = $5)
) m
ORDER BY m.channel_id, m.bucket, m.received_at DESC
`

type GetDeviceMeasurementsRangedParams struct {
	BucketSeconds float64
	DeviceID      pgtype.UUID
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	ChannelID     pgtype.Int2
}

type GetDeviceMeasurementsRangedRow struct {
	ReceivedAt      pgtype.Timestamptz
	ChannelID       int16
	ChannelName     string
	MeasurementType int16
	Value           []byte
}

// Ranged, downsampled measurement fetch. Rows are grouped into fixed-width
// time buckets and the newest reading in each bucket (per channel) is kept as
// the representative data point. The caller picks @bucket_seconds to control
// the resolution. Results are ordered chronologically within each channel.
func (q *Queries) GetDeviceMeasurementsRanged(ctx context.Context, arg GetDeviceMeasurementsRangedParams) ([]GetDeviceMeasurementsRangedRow, error) {
	rows, err := q.db.Query(ctx, getDeviceMeasurementsRanged,
		arg.BucketSeconds,
		arg.DeviceID,
		arg.StartTime,
		arg.EndTime,
		arg.ChannelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceMeasurementsRangedRow
	for rows.Next() {
		var i GetDeviceMeasurementsRangedRow
		if err := rows.Scan(
			&i.ReceivedAt,
			&i.ChannelID,
			&i.ChannelName,
			&i.MeasurementType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesForTokens = `-- name: GetDevicesForTokens :many
SELECT d.id, d.device_eui, d.name, d.latitude, d.longitude
FROM device d
WHERE d.id IN (
	SELECT id FROM device
		WHERE rw_token = ANY($1::TEXT[]) OR ro_token = ANY($1::TEXT[])
	UNION
	SELECT device_group.device_id FROM device_group
		JOIN "group" ON "group".id = device_group.group_id
		WHERE "group".rw_token = ANY($2::TEXT[]) OR "group".ro_token = ANY($2::TEXT[])
)
`

type GetDevicesForTokensParams struct {
	DeviceTokens []string
	GroupTokens  []string
}

type GetDevicesForTokensRow struct {
	ID        pgtype.UUID
	DeviceEui string
	Name      string
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
}

func (q *Queries) GetDevicesForTokens(ctx context.Context, arg GetDevicesForTokensParams) ([]GetDevicesForTokensRow, error) {
	rows, err := q.db.Query(ctx, getDevicesForTokens, arg.DeviceTokens, arg.GroupTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesForTokensRow
	for rows.Next() {
		var i GetDevicesForTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceEui,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMeasurementsForDeviceIDs = `-- name: GetLatestMeasurementsForDeviceIDs :many
SELECT DISTINCT ON (dm.device_id, dm.channel_id)
	dm.device_id,
	dm.received_at,
	dm.channel_id,
	dcm.name AS channel_name,
	dm.measurement_type,
	dm.value
FROM device_measurement dm
JOIN device_channel_mapping dcm
	ON dcm.device_id = dm.device_id AND dcm.channel_id = dm.channel_id
WHERE dm.device_id = ANY($1::UUID[])
ORDER BY dm.device_id, dm.channel_id, dm.received_at DESC
`

type GetLatestMeasurementsForDeviceIDsRow struct {
	DeviceID        pgtype.UUID
	ReceivedAt      pgtype.Timestamptz
	ChannelID       int16
	ChannelName     string
	MeasurementType int16
	Value           []byte
}

func (q *Queries) GetLatestMeasurementsForDeviceIDs(ctx context.Context, deviceIds []pgtype.UUID) ([]GetLatestMeasurementsForDeviceIDsRow, error) {
	rows, err := q.db.Query(ctx, getLatestMeasurementsForDeviceIDs, deviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMeasurementsForDeviceIDsRow
	for rows.Next() {
		var i GetLatestMeasurementsForDeviceIDsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.ReceivedAt,
			&i.ChannelID,
			&i.ChannelName,
			&i.MeasurementType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeviceMeasurement = `-- name: InsertDeviceMeasurement :exec
INSERT INTO device_measurement (device_id, measurement_type, channel_id, "value", received_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertDeviceMeasurementParams struct {
	DeviceID        pgtype.UUID
	MeasurementType int16
	ChannelID       int16
	Value           []byte
	ReceivedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDeviceMeasurement(ctx context.Context, arg InsertDeviceMeasurementParams) error {
	_, err := q.db.Exec(ctx, insertDeviceMeasurement,
		arg.DeviceID,
		arg.MeasurementType,
		arg.ChannelID,
		arg.Value,
		arg.ReceivedAt,
	)
	return err
}

type InsertDeviceMeasurementsParams struct {
	DeviceID        pgtype.UUID
	MeasurementType int16
	ChannelID       int16
	Value           []byte
	ReceivedAt      pgtype.Timestamptz
}
