// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: measurements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeviceMeasurement = `-- name: InsertDeviceMeasurement :exec
INSERT INTO device_measurement (device_id, measurement_type, channel_id, "value", received_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertDeviceMeasurementParams struct {
	DeviceID        pgtype.UUID
	MeasurementType int16
	ChannelID       int16
	Value           []byte
	ReceivedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDeviceMeasurement(ctx context.Context, arg InsertDeviceMeasurementParams) error {
	_, err := q.db.Exec(ctx, insertDeviceMeasurement,
		arg.DeviceID,
		arg.MeasurementType,
		arg.ChannelID,
		arg.Value,
		arg.ReceivedAt,
	)
	return err
}

type InsertDeviceMeasurementsParams struct {
	DeviceID        pgtype.UUID
	MeasurementType int16
	ChannelID       int16
	Value           []byte
	ReceivedAt      pgtype.Timestamptz
}
