// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceMeasurementsRanged = `-- name: GetDeviceMeasurementsRanged :many
SELECT DISTINCT ON (m.channel_id, m.bucket)
	m.received_at,
	m.channel_id,
	m.channel_name,
	m.measurement_type,
	m.value
FROM (
	SELECT
		time_bucket(make_interval(secs => $1::DOUBLE PRECISION), dm.received_at) AS bucket,
		dm.received_at,
		dm.channel_id,
		dcm.name AS channel_name,
		dm.measurement_type,
		dm.value
	FROM device_measurement dm
	JOIN device_channel_mapping dcm
		ON dcm.device_id = dm.device_id AND dcm.channel_id = dm.channel_id
	WHERE dm.device_id = $2
		AND dm.received_at >= $3
		AND dm.received_at <= $4
		AND ($5::SMALLINT IS NULL OR dm.channel_id = $5)
) m
ORDER BY m.channel_id, m.bucket, m.received_at DESC
`

type GetDeviceMeasurementsRangedParams struct {
	BucketSeconds float64
	DeviceID      pgtype.UUID
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	ChannelID     pgtype.Int2
}

type GetDeviceMeasurementsRangedRow struct {
	ReceivedAt      pgtype.Timestamptz
	ChannelID       int16
	ChannelName     string
	MeasurementType int16
	Value           []byte
}

// Ranged, downsampled measurement fetch. Rows are grouped into fixed-width
// time buckets and the newest reading in each bucket (per channel) is kept as
// the representative data point. The caller picks @bucket_seconds to control
// the resolution. Results are ordered chronologically within each channel.
func (q *Queries) GetDeviceMeasurementsRanged(ctx context.Context, arg GetDeviceMeasurementsRangedParams) ([]GetDeviceMeasurementsRangedRow, error) {
	rows, err := q.db.Query(ctx, getDeviceMeasurementsRanged,
		arg.BucketSeconds,
		arg.DeviceID,
		arg.StartTime,
		arg.EndTime,
		arg.ChannelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceMeasurementsRangedRow
	for rows.Next() {
		var i GetDeviceMeasurementsRangedRow
		if err := rows.Scan(
			&i.ReceivedAt,
			&i.ChannelID,
			&i.ChannelName,
			&i.MeasurementType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeviceMeasurement = `-- name: InsertDeviceMeasurement :exec
INSERT INTO device_measurement (device_id, measurement_type, channel_id, "value", received_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertDeviceMeasurementParams struct {
	DeviceID        pgtype.UUID
	MeasurementType int16
	ChannelID       int16
	Value           []byte
	ReceivedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDeviceMeasurement(ctx context.Context, arg InsertDeviceMeasurementParams) error {
	_, err := q.db.Exec(ctx, insertDeviceMeasurement,
		arg.DeviceID,
		arg.MeasurementType,
		arg.ChannelID,
		arg.Value,
		arg.ReceivedAt,
	)
	return err
}

type InsertDeviceMeasurementsParams struct {
	DeviceID        pgtype.UUID
	MeasurementType int16
	ChannelID       int16
	Value           []byte
	ReceivedAt      pgtype.Timestamptz
}
