// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID           pgtype.UUID
	DeviceEui    string
	MinimumLevel float64
}

type DeviceMeasurement struct {
	ReceivedAt pgtype.Timestamptz
	DeviceID   pgtype.UUID
	WaterLevel float64
	Voltage    float64
}
