// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID           pgtype.UUID
	DeviceEui    string
	MinimumLevel float64
}

type DeviceChannelMapping struct {
	DeviceID  pgtype.UUID
	ChannelID interface{}
	Name      string
}

type DeviceMeasurement struct {
	ReceivedAt pgtype.Timestamptz
	DeviceID   pgtype.UUID
	Value      []byte
	ChannelID  interface{}
	Type       interface{}
}
