on:
  - push
  - workflow_dispatch

name: Analysis Static - Datadog

permissions:
  contents: read
  security-events: write

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Pipeline started
        run: echo "Checking preconditions for static analysis"

  static-analysis:
    needs: setup
    if: secrets.DD_API_KEY != '' && secrets.DD_APP_KEY != ''
    runs-on: ubuntu-latest
    name: Datadog Static Analyzer
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check code meets quality and security standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_site: datadoghq.eu
        cpu_count: 2
