name: PlatformIO CI

on: [push, pull_request]

permissions:
  contents: read # for checkout
  packages: write
  actions: write # for cache

jobs:
  build:
    name: Build Environments
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ["heltec_wifi_lora_32_V3_HCSR04"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build firmware
        run: pio run -e ${{ matrix.environment }}
      - uses: actions/upload-artifact@v2
        with:
          name: firmware-${{ matrix.environment }}
          path: |
            .pio/build/${{ matrix.environment }}/*.bin
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: firmware-release
          path: .pio/build/${{ matrix.environment }}/*.bin

  #  release:
  #    name: Create Release
  #    runs-on: ubuntu-latest
  #    needs: [build]
  #    if: startsWith(github.ref, 'refs/tags/')
  #    steps:
  #      - uses: actions/download-artifact@v2
  #        with:
  #          name: firmware-release
  #      - name: Create draft release
  #        uses: softprops/action-gh-release@v1
  #        with:
  #          draft: True
  #          files: |
  #            *.bin
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #

  release_semantic:
    name: Release semantique
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
