name: Add issue automaticall to project

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add To GitHub projects
      uses: actions/add-to-project@v1.0.2
      with:
        # URL of the project to add issues to
        project-url: https://github.com/orgs/ttnleipzig/projects/1
        github-token: ${{ secrets.PROJECTS_TOKEN }}
        # labeled:  optional
        # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
        # label-operator: # optional

