name: Add issue automaticall to project

on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:

  add-to-project:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Add To GitHub projects
      uses: actions/add-to-project@v1.0.2
      with:
        # URL of the project to add issues to
        project-url: https://github.com/orgs/ttnleipzig/projects
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # labeled:  optional
        # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
        # label-operator: # optional

