name: Sketch - release

on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: write

jobs:

  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["heltec_wifi_lora_32_V3_HCSR04"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build firmware
        run: pio run -e ${{ matrix.environment }}
      - name: Display contents of .pio/build directory
        run: |
            ls -R .pio/build
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: .pio/build/${{ matrix.environment }}/*.bin
          compression-level: 8

  release:
    name: 📦 Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      upload-url: ${{ steps.release.outputs.upload_url }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_ORGANISATION }}
          release-type: simple
      - name: Print the release URL if present
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"


  upload:
    name: 💾 Upload Artifacts
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs: release
    strategy:
      matrix:
        environment: ["heltec_wifi_lora_32_V3_HCSR04"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: firmware
      - name: Create firmware zip
        run: zip -r regenfass-${{ matrix.environment }}.zip firmware/
      - name: Upload firmware to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release.outputs.tag-name }} \
            firmware/firmware.bin#regenfass-${{ matrix.environment }}.bin \
            regenfass-${{ matrix.environment }}.zip \
            --repo ${{ github.repository }}
