name: Sketch - pull request

on:
  pull_request:
    branches:
      - feat/*
      - fix/*
      - ci/*
      - style/*
      - docs/*

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    name: Build Environments
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ["heltec_wifi_lora_32_V3_HCSR04"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build firmware
        run: pio run -e ${{ matrix.environment }}

      - name: Extract firmware metadata
        run: >-
          pio project metadata -e '${{ matrix.environment }}' --json-output |
           jq '.${{ matrix.environment }}.extra' > .pio/build/${{ matrix.environment }}/firmware_metadata.json

      - uses: actions/upload-artifact@v2
        with:
          name: firmware-${{ matrix.environment }}
          path: |
            .pio/build/${{ matrix.environment }}/firmware.bin
            .pio/build/${{ matrix.environment }}/bootloader.bin
            .pio/build/${{ matrix.environment }}/firmware_metadata.json
